reg.steam.key.32 = HKEY_LOCAL_MACHINE\\SOFTWARE\\Valve\\Steam
reg.steam.key.64 = HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Valve\\Steam
reg.steam.install.path = InstallPath
steam.libraryfolders.file = \\steamapps\\libraryfolders.vdf

warselection.dir = autodetect
warselection.path = \\steamapps\\common\\War Selection
warselection.app.id = 1022450

warselection.root.folder = \\Cache
# relative to the game directory, not to the root folder
warselection.engine.version.file = \\engine-version.txt
warselection.main.file = \\Projects\\WarSelection\\main.json
warselection.gameplay.file = \\Projects\\WarSelection\\gameplay.json
warselection.visual.file = \\Projects\\WarSelection\\visual.json
warselection.localization.folder = \\Projects\\WarSelection\\localization
warselection.interfaces.session.init.file = \\Content\\interfaces\\WarSelection\\session\\scripts\\_init.lua
warselection.interfaces.session.start.file = \\Content\\interfaces\\WarSelection\\session\\scripts\\_start.lua
warselection.on.project.load.file = \\Projects\\WarSelection\\scripts\\main\\onProjectLoad.lua
warselection.cultures.file = \\Projects\\WarSelection\\scripts\\common\\cultures.lua
warselection.env.names.file = \\Projects\\WarSelection\\scripts\\common\\envNames.lua
warselection.research.icons.file = \\CommonScripts\\interface\\WarSelection\\researchIcons.lua
warselection.content.namespace = WarSelection
warselection.content.units.folder = \\Content\\units\\WarSelection
warselection.content.envs.folder = \\Content\\envs\\WarSelection
warselection.content.projectiles.folder = \\Content\\projectiles\\WarSelection
warselection.content.ui.folder = \\Content\\ui
image.file.extension = png
localization.key.names = upgrade,unitName,nationName,unitText,envName,unitTag,unitSearchTag,envSearchTag,recourceName
