package com.wsunitstats.exporter.model.exported.submodel.research;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Is not related to game files data. Generated by the app
 */
@Getter
@Setter
@ToString
public class UpgradeMetadataModel {
    private String description;
}
